src/Site/MainBundle/Entity/Slider.php
<?php

namespace Site\MainBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\HttpFoundation\File\UploadedFile;

/**
 * Site\MainBundle\Entity\Slider
 *
 * @ORM\Table(name="slider")
 * @ORM\Entity(repositoryClass="Site\MainBundle\Entity\Repository\SliderRepository")
 */
class Slider
{
    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=512, nullable=true)
     */
    private $title1;

    /**
     * @ORM\Column(type="string", length=512, nullable=true)
     */
    private $title2;

    /**
     * @ORM\Column(type="string", length=512, nullable=true)
     */
    private $link;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $img;

    /**
     * @Assert\File()
     */
    private $file;

    /**
     * @ORM\Column(type="boolean")
     */
    private $main = false;

    /**
     * @var integer
     * @ORM\Column(name="position", type="integer", nullable=true)
     */
    private $position = 0;

    public function getAbsolutePath()
    {
        return null === $this->img
            ? null
            : $this->getUploadRootDir().'/'.$this->img;
    }

    public function getWebPath()
    {
        return null === $this->img
            ? null
            : $this->getUploadDir().'/'.$this->img;
    }

    protected function getUploadRootDir()
    {
        return __DIR__.'/../../../../../'.$this->getUploadDir();
    }

    protected function getUploadDir()
    {
        return 'uploads/slider';
    }

    /**
     * Sets file.
     *
     * @param UploadedFile $file
     */
    public function setFile(UploadedFile $file = null)
    {
        $this->file = $file;

        $this->upload();
    }

    /**
     * Get file.
     *
     * @return UploadedFile
     */
    public function getFile()
    {
        return $this->file;
    }

    public function upload()
    {
        if (null === $this->getFile()) {
            return;
        }

        if (isset($this->img)) {
            if(file_exists($this->getUploadDir().'/'.$this->img)){
                unlink($this->getUploadDir().'/'.$this->img);
            }
            $this->img = null;
        }

        $this->img = $this->getFile()->getClientOriginalName();

        $this->getFile()->move(
            $this->getUploadDir(),
            $this->img
        );

        $this->file = null;
    }

    /**
     * Get id
     *
     * @return integer 
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set img
     *
     * @param string $img
     * @return Slider
     */
    public function setImg($img)
    {
        $this->img = $img;

        return $this;
    }

    /**
     * Get img
     *
     * @return string 
     */
    public function getImg()
    {
        return $this->img;
    }

    /**
     * Set main
     *
     * @param boolean $main
     * @return Slider
     */
    public function setMain($main)
    {
        $this->main = $main;

        return $this;
    }

    /**
     * Get main
     *
     * @return boolean 
     */
    public function getMain()
    {
        return $this->main;
    }

    /**
     * Set position
     *
     * @param integer $position
     * @return Slider
     */
    public function setPosition($position)
    {
        $this->position = $position;

        return $this;
    }

    /**
     * Get position
     *
     * @return integer 
     */
    public function getPosition()
    {
        return $this->position;
    }

    /**
     * Set title1
     *
     * @param string $title1
     *
     * @return Slider
     */
    public function setTitle1($title1)
    {
        $this->title1 = $title1;

        return $this;
    }

    /**
     * Get title1
     *
     * @return string
     */
    public function getTitle1()
    {
        return $this->title1;
    }

    /**
     * Set title2
     *
     * @param string $title2
     *
     * @return Slider
     */
    public function setTitle2($title2)
    {
        $this->title2 = $title2;

        return $this;
    }

    /**
     * Get title2
     *
     * @return string
     */
    public function getTitle2()
    {
        return $this->title2;
    }

    /**
     * Set link
     *
     * @param string $link
     *
     * @return Slider
     */
    public function setLink($link)
    {
        $this->link = $link;

        return $this;
    }

    /**
     * Get link
     *
     * @return string
     */
    public function getLink()
    {
        return $this->link;
    }
}

src/Site/MainBundle/Form/SliderType.php
<?php

namespace Site\MainBundle\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolverInterface;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\UrlType;

class SliderType extends AbstractType
{
    /**
     * @param FormBuilderInterface $builder
     * @param array $options
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('title1', null, array(
                'required' => false,
                'label' => 'backend.slider.title1'
            ))
            ->add('title2', null, array(
                'required' => false,
                'label' => 'backend.slider.title2'
            ))
            ->add('link', UrlType::class, array(
                'required' => false,
                'label' => 'backend.slider.link'
            ))
            ->add('position', null, array(
                'required' => false,
                'label' => 'backend.slider.position',
                'attr' => array(
                    'min' => 0
                )
            ))
            ->add('file', FileType::class, array(
                'required' => false,
                'label' => 'backend.slider.img'
            ))
            ->add('main', ChoiceType::class, array(
                'required' => true,
                'label' => 'backend.slider.main',
                'choices' => array(
                    'backend.slider.main_no' => 0,
                    'backend.slider.main_yes' => 1
                )
            ))
        ;
    }
    
    /**
     * @param OptionsResolverInterface $resolver
     */
    public function setDefaultOptions(OptionsResolverInterface $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => 'Site\MainBundle\Entity\Slider'
        ));
    }

    /**
     * @return string
     */
    public function getName()
    {
        return 'site_mainbundle_slider';
    }
}

src/Site/MainBundle/Controller/Backend/ClientController.php
<?php

namespace Site\MainBundle\Controller\Backend;

use Symfony\Component\HttpFoundation\Request;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;

use Site\MainBundle\Entity\Client;
use Site\MainBundle\Form\ClientType;

/**
 * Client controller.
 *
 */
class ClientController extends Controller
{

    /**
     * Lists all Client entities.
     *
     */
    public function indexAction()
    {
        $em = $this->getDoctrine()->getManager();

        $entities = $em->getRepository('SiteMainBundle:Client')->findAll();

        $paginator = $this->get('knp_paginator');
        $pagination = $paginator->paginate(
            $entities,
            $this->get('request')->query->get('page', 1) /*client number*/,
            10/*limit per client*/
        );

        return $this->render('SiteMainBundle:Backend/Client:index.html.twig', array(
            'entities' => $pagination,
        ));
    }

    /**
     * Creates a new Client entity.
     *
     */
    public function createAction(Request $request)
    {
        $entity = new Client();
        $form = $this->createCreateForm($entity);
        $form->handleRequest($request);

        if ($form->isValid()) {
            $em = $this->getDoctrine()->getManager();
            $em->persist($entity);
            $em->flush();

            return $this->redirect($this->generateUrl('backend_client_show', array('id' => $entity->getId())));
        }

        return $this->render('SiteMainBundle:Backend/Client:new.html.twig', array(
            'entity' => $entity,
            'form'   => $form->createView(),
        ));
    }

    /**
     * Creates a form to create a Client entity.
     *
     * @param Client $entity The entity
     *
     * @return \Symfony\Component\Form\Form The form
     */
    private function createCreateForm(Client $entity)
    {
        $form = $this->createForm(new ClientType(), $entity, array(
            'action' => $this->generateUrl('backend_client_create'),
            'method' => 'POST',
        ));

        $form->add('submit', 'submit', array('label' => 'backend.create'));

        return $form;
    }

    /**
     * Displays a form to create a new Client entity.
     *
     */
    public function newAction()
    {
        $entity = new Client();
        $form   = $this->createCreateForm($entity);

        return $this->render('SiteMainBundle:Backend/Client:new.html.twig', array(
            'entity' => $entity,
            'form'   => $form->createView(),
        ));
    }

    /**
     * Finds and displays a Client entity.
     *
     */
    public function showAction($id)
    {
        $em = $this->getDoctrine()->getManager();

        $entity = $em->getRepository('SiteMainBundle:Client')->find($id);

        if (!$entity) {
            throw $this->createNotFoundException($this->get('translator')->trans('backend.client.not_found'));
        }

        $deleteForm = $this->createDeleteForm($id);

        return $this->render('SiteMainBundle:Backend/Client:show.html.twig', array(
            'entity'      => $entity,
            'delete_form' => $deleteForm->createView(),
        ));
    }

    /**
     * Displays a form to edit an existing Client entity.
     *
     */
    public function editAction($id)
    {
        $em = $this->getDoctrine()->getManager();

        $entity = $em->getRepository('SiteMainBundle:Client')->find($id);

        if (!$entity) {
            throw $this->createNotFoundException($this->get('translator')->trans('backend.client.not_found'));
        }

        $editForm = $this->createEditForm($entity);
        $deleteForm = $this->createDeleteForm($id);

        return $this->render('SiteMainBundle:Backend/Client:edit.html.twig', array(
            'entity'      => $entity,
            'edit_form'   => $editForm->createView(),
            'delete_form' => $deleteForm->createView(),
        ));
    }

    /**
    * Creates a form to edit a Client entity.
    *
    * @param Client $entity The entity
    *
    * @return \Symfony\Component\Form\Form The form
    */
    private function createEditForm(Client $entity)
    {
        $form = $this->createForm(new ClientType(), $entity, array(
            'action' => $this->generateUrl('backend_client_update', array('id' => $entity->getId())),
            'method' => 'PUT',
        ));

        $form->add('submit', 'submit', array('label' => 'backend.update'));

        return $form;
    }
    /**
     * Edits an existing Client entity.
     *
     */
    public function updateAction(Request $request, $id)
    {
        $em = $this->getDoctrine()->getManager();

        $entity = $em->getRepository('SiteMainBundle:Client')->find($id);

        if (!$entity) {
            throw $this->createNotFoundException($this->get('translator')->trans('backend.client.not_found'));
        }

        $deleteForm = $this->createDeleteForm($id);
        $editForm = $this->createEditForm($entity);
        $editForm->handleRequest($request);

        if ($editForm->isValid()) {
            $em->flush();

            return $this->redirect($this->generateUrl('backend_client_show', array('id' => $id)));
        }

        return $this->render('SiteMainBundle:Backend/Client:edit.html.twig', array(
            'entity'      => $entity,
            'edit_form'   => $editForm->createView(),
            'delete_form' => $deleteForm->createView(),
        ));
    }
    /**
     * Deletes a Client entity.
     *
     */
    public function deleteAction(Request $request, $id)
    {
        $form = $this->createDeleteForm($id);
        $form->handleRequest($request);

        if ($form->isValid()) {
            $em = $this->getDoctrine()->getManager();
            $entity = $em->getRepository('SiteMainBundle:Client')->find($id);

            if (!$entity) {
                throw $this->createNotFoundException($this->get('translator')->trans('backend.client.not_found'));
            }

            $em->remove($entity);
            $em->flush();
        }

        return $this->redirect($this->generateUrl('backend_client_index'));
    }

    /**
     * Creates a form to delete a Client entity by id.
     *
     * @param mixed $id The entity id
     *
     * @return \Symfony\Component\Form\Form The form
     */
    private function createDeleteForm($id)
    {
        return $this->createFormBuilder()
            ->setAction($this->generateUrl('backend_client_delete', array('id' => $id)))
            ->setMethod('DELETE')
            ->add('submit', 'submit', array(
                'label' => 'backend.delete',
                'translation_domain' => 'menu',
                'attr' => array(
                    'class' => 'btn-danger'
                )
            ))
            ->getForm()
        ;
    }

    /**
     * Экспорт в excel
     *
     * @return mixed
     */
    public function exportAction()
    {
        return $this->get('export.excel')->export();
    }
}

src/Site/MainBundle/Controller/Backend/DashboardController.php
<?php

namespace Site\MainBundle\Controller\Backend;

use Symfony\Component\HttpFoundation\Request;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;

/**
 * Dashboard controller.
 *
 */
class DashboardController extends Controller
{

    public function indexAction()
    {
        return $this->render('SiteMainBundle:Backend/Dashboard:index.html.twig');
    }

}

src/Site/MainBundle/Resources/views/Backend/Slider/edit.html.twig
{% extends 'SiteMainBundle:Backend:layout.html.twig' %}

{% block content -%}
    <h1>{{ 'backend.slider.h1_edit'|trans }}</h1>

    {{ form(delete_form) }}

    {{ form(edit_form, { 'style': 'horizontal', attr: {novalidate: 'novalidate'} }) }}

    <ul class="record_actions nav nav-pills">
        <li>
            <a href="{{ path('backend_slider_index') }}">
                {{ 'backend.slider.back_to_list'|trans }}
            </a>
        </li>
    </ul>
{% endblock %}

src/Site/MainBundle/Resources/views/Backend/Slider/index.html.twig
{% extends 'SiteMainBundle:Backend:layout.html.twig' %}

{% block content -%}
    <h1>{{ 'backend.slider.h1_list'|trans }}</h1>

    {% if entities|length > 0 %}
        <table class="records_list table table-striped table-bordered">
            <thead>
            <tr>
                <th>Id</th>
                <th>{{ 'backend.slider.position'|trans }}</th>
                <th>{{ 'backend.slider.img'|trans }}</th>
                <th>{{ 'backend.slider.main'|trans }}</th>
                <th>{{ 'backend.actions'|trans }}</th>
            </tr>
            </thead>
            <tbody>
            {% for entity in entities %}
                <tr>
                    <td><a href="{{ path('backend_slider_show', { 'id': entity.id }) }}">{{ entity.id }}</a></td>
                    <td>{{ entity.position }}</td>
                    <td>{% if entity.webPath|length > 0 %}<a href="{{ asset(entity.webPath) }}" target="_blank"><img src="{{ image(entity.webPath).resize(150) }}" alt="{{ image(entity.webPath).resize(150) }}" width="150px"/></a>{% endif %}</td>
                    <td>{{ (entity.main ? 'backend.slider.main_yes' : 'backend.slider.main_no')|trans }}</td>
                    <td>
                        <ul class="nav nav-pills">
                            <li>
                                <a href="{{ path('backend_slider_show', { 'id': entity.id }) }}">{{ 'backend.show'|trans }}</a>
                            </li>
                            <li>
                                <a href="{{ path('backend_slider_edit', { 'id': entity.id }) }}">{{ 'backend.edit'|trans }}</a>
                            </li>
                        </ul>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
        {{ knp_pagination_render(entities) }}
    {% else %}
        <div class="alert alert-warning">
            {{ 'backend.slider.empty_list'|trans }}
        </div>
    {% endif %}

    <ul class="nav nav-pills">
        <li class="active">
            <a href="{{ path('backend_slider_new') }}">
                {{ 'backend.create'|trans }}
            </a>
        </li>
    </ul>
{% endblock %}

src/Site/MainBundle/Resources/views/Backend/Slider/new.html.twig
{% extends 'SiteMainBundle:Backend:layout.html.twig' %}

{% block content -%}
    <h1>{{ 'backend.slider.h1_create'|trans }}</h1>

    {{ form(form, { 'style': 'horizontal', attr: {novalidate: 'novalidate'} }) }}

    <ul class="record_actions nav nav-pills">
        <li>
            <a href="{{ path('backend_slider_index') }}">
                {{ 'backend.slider.back_to_list'|trans }}
            </a>
        </li>
    </ul>
{% endblock %}

src/Site/MainBundle/Resources/views/Backend/Slider/show.html.twig
{% extends 'SiteMainBundle:Backend:layout.html.twig' %}

{% block content -%}
    <h1>{{ 'backend.slider.h1_show'|trans }}</h1>

    {{ form(delete_form) }}

    <table class="record_properties table table-striped table-bordered">
        <tbody>
        <tr>
            <th>Id</th>
            <td>{{ entity.id }}</td>
        </tr>
        <tr>
            <th>{{ 'backend.slider.title1'|trans }}</th>
            <td>{{ entity.title1 }}</td>
        </tr>
        <tr>
            <th>{{ 'backend.slider.title2'|trans }}</th>
            <td>{{ entity.title2 }}</td>
        </tr>
        <tr>
            <th>{{ 'backend.slider.link'|trans }}</th>
            <td>{{ entity.link }}</td>
        </tr>
        <tr>
            <th>{{ 'backend.slider.position'|trans }}</th>
            <td>{{ entity.position }}</td>
        </tr>
        <tr>
            <th>{{ 'backend.slider.img'|trans }}</th>
            <td>{% if entity.webPath|length > 0 %}<a href="{{ asset(entity.webPath) }}" target="_blank"><img src="{{ image(entity.webPath).resize(150) }}" alt="{{ image(entity.webPath).resize(150) }}" width="150px"/></a>{% endif %}</td>
        </tr>
        <tr>
            <th>{{ 'backend.slider.main'|trans }}</th>
            <td>{{ (entity.main ? 'backend.slider.main_yes' : 'backend.slider.main_no')|trans }}</td>
        </tr>
        </tbody>
    </table>

    <ul class="record_actions nav nav-pills">
        <li>
            <a href="{{ path('backend_slider_index') }}">
                {{ 'backend.slider.back_to_list'|trans }}
            </a>
        </li>
        <li>
            <a href="{{ path('backend_slider_edit', { 'id': entity.id }) }}">
                {{ 'backend.edit'|trans }}
            </a>
        </li>
        <li>
            <a href="{{ path('backend_slider_new') }}">
                {{ 'backend.create'|trans }}
            </a>
        </li>
    </ul>
{% endblock %}